### ISSUE TITLE
When do you plan to release the code?

### ISSUE THREAD

**Issue by Aolius** [aistairc/contrastive_data2text#1]
Hi, thank you for sharing your work, which is quite interesting to me.
I was wondering when you plan to release the code.

**Comment by ibadora** [comment]
Thank you for taking interest on our work!
Our institution recently approved the release of the code and we will start preparing the release.

Just for your information, our previous work on market comment generation is now publicly available:
https://github.com/aistairc/market-reporter

**Comment by ibadora** [comment]
We now pushed the code. I hope this will help you.

**Comment by Aolius** [comment]
Thanks!
